### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by krischer** [fraxen/tectonicplates#2]
Hi,

thanks a lot for this. Looks great!

We are thinking about including this into an LGPL licensed open source software package of ours (obspy/obspy#921) and are wondering if your ODC license clashes with any of the original author's rights. Did you check with them or do you have any expert knowledge that it is ok? We are no lawyers so we would just like to make sure its alright to use it.

Cheers and thanks a lot!

Lion

**Comment by fraxen** [comment]
The LGPL is not relevant is it? I communicated with the original author when I prepared this repo, and he has approved it (including the license and the text). I think it should be fine as long as you credit the author.

**Comment by krischer** [comment]
Thanks for the clarification! That is good enough for us.
